spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rltjr219@gmail.com
    password: didrltjr3!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true