spring:
  profiles:
    include: real-db, mail
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties : true
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rltjr219@gmail.com
    password: didrltjr3
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app-property:
  test-email: user@email.com
  test-password: password
  test-nickname: DNDpickme
  test-another-email: another@email.com
  test-another-nickname: springmaster
  test-registration-number: 01-2345-6789
  test-name: KSU
  test-address: BUSAN
  test-ceo-name: sangyeop

image:
  location: ../pickme-images

server:
  port: 8083